baseURL = "http://wy-cs.info"
languageCode = "en-us"
title = "WY Computer Science"
theme = "docdock"
publishDir = "docs"
theme_variant = "docmo"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>Other</h3>"
name = "Biography"
url = "/biography"

[[menu.shortcuts]]
pre = "<h3>External</h3>"
name = "<i class='fa fa-calendar' aria-hidden='true'></i>AP Exam Calendar 2018"
identifier = "apcal"
url = "https://apcentral.collegeboard.org/courses/exam-dates-and-fees"
weight = 5

[[menu.shortcuts]]
name = "Whitney Young"
identifier = "wy"
url = "http://wyoung.org"
weight = 10

